# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='team_name',
        ),
    ]
