# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_remove_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
