# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20160715_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
