# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0010_auto_20160719_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='players',
        ),
        migrations.AddField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
