# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_auto_20160720_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='password',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
