# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_auto_20160722_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='special_user',
            new_name='special_users',
        ),
    ]
