# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_auto_20160722_0332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialUser',
            new_name='TypeUser',
        ),
    ]
