# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_auto_20160722_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='league',
            name='special_users',
        ),
        migrations.DeleteModel(
            name='SpecialUser',
        ),
    ]
