# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_auto_20160725_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_notification',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade_notification',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
