# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_auto_20160727_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='current_ranking',
            field=models.IntegerField(default=0),
        ),
    ]
