# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0024_history_current_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Pairings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User_Match_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=None)),
                ('tie', models.BooleanField(default=None)),
                ('match_pairing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.Match_Pairings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match_pairings',
            name='details',
            field=models.ManyToManyField(default=None, to='league.User_Match_Details'),
        ),
        migrations.AddField(
            model_name='match_pairings',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AddField(
            model_name='match_pairings',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
