# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_auto_20160728_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
    ]
