# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 20:39
from __future__ import unicode_literals

from django.db import migrations
import league.models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_league_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='pairings',
            field=league.models.ListField(default=None),
        ),
    ]
