# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_league_pairings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='last_game',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
