# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0030_auto_20160803_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.FileField(default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='/fantPictures'),
            preserve_default=False,
        ),
    ]
