# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='/fantPictures'),
        ),
    ]
