# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0033_auto_20160812_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.League'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='user',
        ),
        migrations.AddField(
            model_name='user_match_details',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
