# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0035_match_pairings_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_pairings',
            name='users',
        ),
        migrations.AlterField(
            model_name='user_match_details',
            name='tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_match_details',
            name='user',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_match_details',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
