# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0037_match_pairings_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_pairings',
            name='details',
        ),
        migrations.RemoveField(
            model_name='match_pairings',
            name='league',
        ),
        migrations.RemoveField(
            model_name='match_pairings',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='match_pairing',
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='tie',
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='winner',
        ),
    ]
