# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0039_auto_20160816_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_pairings',
            name='details',
            field=models.ManyToManyField(default=None, to='league.User_Match_Details'),
        ),
        migrations.AddField(
            model_name='match_pairings',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_match_details',
            name='match_pairing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.Match_Pairings'),
        ),
        migrations.AddField(
            model_name='user_match_details',
            name='tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_match_details',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_match_details',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match_pairings',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_match_details',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
