# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0043_auto_20160817_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_match_details',
            name='user',
        ),
    ]
