# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0045_user_match_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_match_details',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
