# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0046_auto_20160821_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_match_details',
            name='match_pairing',
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='tie',
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_match_details',
            name='winner',
        ),
    ]
