# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0047_auto_20160821_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_match_details',
            name='match_pairing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='league.Match_Pairings'),
        ),
        migrations.AddField(
            model_name='user_match_details',
            name='tie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_match_details',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_match_details',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_match_details',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
