# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0048_auto_20160821_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_match_details',
            name='bye',
            field=models.BooleanField(default=False),
        ),
    ]
